name: Extractor Diario de Herramientas IA

on:
  schedule:
    # Ejecutar todos los días a las 9:00 AM UTC (10:00 AM CET)
    - cron: '0 9 * * *'
  workflow_dispatch:  # Permite ejecutar manualmente

jobs:
  extraer-herramientas:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
    
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_simple.txt
    
    - name: Crear archivo de credenciales de Google
      run: |
        echo '${{ secrets.GOOGLE_CREDENTIALS }}' > credentials.json
    
    - name: Ejecutar extractor
      run: |
        python ai_tools_scraper_simple.py
    
    - name: Limpiar credenciales
      if: always()
      run: |
        rm -f credentials.json

